# Generated by Django 5.1.2 on 2024-10-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
